Codigo da equipe: E04
Componentes: 

Ana Paula Tartari Seidenstucker       ana.seidenstucker@ucsal.edu.br   71 9 9397-0202
Gean Carlos de Souza Almeida          gean.almeida@ucsal.edu.br        71 9 9673-2001
Italo Gabriel Rocha Lino              italo.lino@ucsal.edu.br          71 9 8742-1452
Felipe Augusto da E. Moreira          felipea.moreira@ucsal.edu.br     71 9 8775-6078

>> Relatório da análise léxica <<

Lexeme                          |  Átomo  | Índice na Tabela de Símbolos
Calculadora                     |   I02   | 1
CalculadoraCalculadoraCalculad  |   I02   | 2
tipo-func                       |   P14   | ---
inteiro                         |   P10   | ---
:                               |   S04   | ---
soma                            |   I03   | 3
real                            |   P09   | ---
false                           |   I02   | 4
tipo-var                        |   P07   | ---
se                              |   P17   | ---
123                             |   I04   | 5
abc                             |   I02   | 6
'a'                             |   I07   | 7
teste                           |   I02   | 8
programa                        |   P01   | ---
declaracoes                     |   P02   | ---
x                               |   ???   | 9
;                               |   S01   | ---
fim-declaracoes                 |   P03   | ---
funcoes                         |   P04   | ---
soma                            |   I02   | 3
(                               |   S06   | ---
tipo-param                      |   P16   | ---
y                               |   I02   | 10
,                               |   S05   | ---
z                               |   I02   | 11
)                               |   S07   | ---
{                               |   S09   | ---
retorna                         |   P22   | ---
+                               |   S16   | ---
}                               |   S10   | ---
fim-funcoes                     |   P05   | ---
fim-programa                    |   P06   | ---
