Relatório da análise léxica

Lexeme                          |  Átomo  | Índice na Tabela de Símbolos
"15 ANA d"                      |   I06   | 1
'a'                             |   I07   | 2
a                               |   I02   | 3
d                               |   I02   | 4
programa                        |   X00   | 4
Calculadora                     |   I01   | 5
declaracoes                     |   X00   | 5
tipo-var                        |   X00   | 5
inteiro                         |   X00   | 5
:                               |   S04   | 5
x                               |   I02   | 6
;                               |   S01   | 6
fim-declaracoes                 |   X00   | 6
funcoes                         |   X00   | 6
tipo-func                       |   X00   | 6
inteiro                         |   X00   | 6
:                               |   S04   | 6
soma                            |   I02   | 7
(                               |   S06   | 7
tipo-param                      |   X00   | 7
inteiro                         |   X00   | 7
:                               |   S04   | 7
y                               |   I02   | 8
,                               |   S05   | 8
z                               |   I02   | 9
)                               |   S07   | 9
{                               |   S09   | 9
retorna                         |   X00   | 9
y                               |   I02   | 8
+                               |   S16   | 8
z                               |   I02   | 9
;                               |   S01   | 9
}                               |   S10   | 9
fim-funcoes                     |   X00   | 9
fim-programa                    |   X00   | 9
